# Generated by Django 6.0.3 on 2026-04-06 03:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('state', models.JSONField(help_text='Array of celestial body definitions')),
                ('settings', models.JSONField(default=dict, help_text='Simulation settings: integrator, timeStep, etc.')),
                ('thumbnail', models.CharField(default='🌍', help_text='Emoji thumbnail', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Untitled Simulation', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('state', models.JSONField(default=list, help_text='Array of body objects: {type, name, mass, radius, position, velocity, color, ...}')),
                ('sim_settings', models.JSONField(default=dict, help_text='Simulation settings: integrator, timeStep, trailLength, etc.')),
                ('share_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField()),
                ('sim_time', models.FloatField(help_text='Simulation time at snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='simulator.simulation')),
            ],
            options={
                'ordering': ['sim_time'],
            },
        ),
    ]
